apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-maven-settings
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <servers>
      <server>
      <id>github</id>
      <username>iamvvra</username>
      <password>Theriyathu@08</password>
    </server>
    </servers>
