{{ if .Values.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end -}}